### PR TITLE
added view to mark notifications as read and better filtering of noti…

### LINKED ISSUE #84: Edit comment feature

### LINKED ISSUE #93: Mark all as read - Notifications

### PR DESCRIPTION
**Pull request by muremwa**
…fications. closes #93

### CODE REVIEW

**Comment by gjergjk71** [comment]
Thanks for the contribution :) 

I'll review when I find time but I'm pretty busy with work these days :/ .

**Comment by muremwa** [comment]
Sounds good.

**Comment by tsarchghs** [comment]
Looks good :)

On another note: This project could use a more user-friendly approach to performing actions, if you're comfortable with ajax and have the time, I'd appreciate if you made for example in edit profile, saving the changes possible without refreshing, you'd need to implement the API endpoint and then use it on the client-side.

On yet another note: I can't believe me of 2018 just thought that getting all the notifications and filtering from client-side is a good idea 😅

**Comment by muremwa** [comment]
I'll get time and work on it.

**Pull request merged**
